pipeline { 
    agent any  
    stages { 
        stage('Stage1') { 
            steps { 
               echo 'This is my first simple pipeline example. Stage1' 
            }
        }
		 stage('Stage2') { 
            steps { 
               echo 'This is my first simple pipeline example. Stage2' 
            }
        }
    }
}