pipeline 
{ 
    agent any 
	tools {
        maven 'Maven3.6' 
    }
    stages 
	{ 
        stage('Check Maven Version') 
		{ 
            steps 
			{ 
               sh 'mvn --version'
            }
        }
    }
}