pipeline 
{ 
    agent any 
	tools {
        maven 'Maven3.6' 
    }
    stages 
	{ 
        stage('Compile Stage') 
		{ 
            steps 
			{ 
               echo 'This is my first Pipeline with Maven example.' 			 			   
			     bat 'mvn clean compile'
            }
        }
    }
}