pipeline 
{ 
    agent any 
     tools { 
        maven 'maven-3.6' 
        jdk 'java-1.8' 
    }
    stages 
	{ 
         stage('Testing echo') 
	 {
            steps 
        	{  
	        echo 'Hello machiii'
               }
        }
	stage ('Initialize Env')
	{
            steps 
	     {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${MAVEN_HOME}"
                ''' 
             }
        }	
		
    }
}
